### PR TITLE
feat: firstLastPiecePrio

### PR DESCRIPTION
**Pull request by s0up4200**

### CODE REVIEW

**Review by zze0s — COMMENTED** [review]
Looks like we can set the property directly on addTorrent <https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-torrent> with `firstLastPiecePrio: true`.

**Comment by s0up4200** [comment]
> Looks like we can set the property directly on addTorrent <https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-torrent> with `firstLastPiecePrio: true`.

Can just revert https://github.com/autobrr/go-qbittorrent/commit/a8b4232e38e9ef047efdbd741a7cb8f36b83424b then I guess? Still need it in domain.go right?

**Comment by s0up4200** [comment]
Tested locally. Property was enabled as expected in qBit 4.3.9 👍 
CleanShot 2024-04-18 at 12 08 53@2x

**Review by zze0s — APPROVED** [review]
👍

**Pull request merged**
